### ISSUE TITLE
Move map with user

### ISSUE THREAD

**Issue by magnhan** [heyloft/maraudersmap#4]
### Description:
This is dependent on #1 to be completed. Also dependent on #8, but could work without if we use some kind of mock data.
### Tasks:
- [x] ios
- [ ] android

**Comment by malindst** [comment]
Should be solved with merge request branch #2-show-yourself-on-map-tiles

**Comment by mathiazom** [comment]
This felt more annoying than useful, so closing for now.

**Comment by mathiazom** [comment]
Nvm, we will make a button to toggle this feature
